# Generated by Django 5.0.3 on 2024-06-27 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_e', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
                ('dept_description', models.TextField()),
                ('dept_location', models.TextField()),
                ('dept_budget', models.PositiveBigIntegerField()),
                ('dept_projects', models.TextField()),
                ('dept_goals', models.TextField()),
                ('dept_added_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_added_by_user', to=settings.AUTH_USER_MODEL)),
                ('dept_updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_updated_by_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_dept', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
