# Generated by Django 5.0.3 on 2024-06-28 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_e', '0003_rank_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank1', to='hrm_e.rank'),
        ),
    ]
